# filename: Makefile
#  	Data Structures (V22.0102)
#  	Fall 2010, Professor Yap
#################################
# 
#  This is simple Makefile for compiling and executing Java programs.
#
#  It is deliberately minimalist.
# 
#  USAGE:
#    1. To run the program with default argument, type:
#  	> make r		(Also: "make run")
#
#    2. To run the program with argument XXX, type:
#  	> make r arg=XXX	(Also: "make run arg=XXX")
# 
#    3. To compile the program, type:
#  	> make		(Also: "make c", or "make compile")
#
#
#   Author: C.Yap
#   Date: Sep 8, 2010
#
#################################
# Variables
#################################
# default program:
p=gui/CalcGUI
p2=backend/CalcBackend

# default argument:
#arg=

#################################
# Targets
#################################
# default target:
c compile javac:
	javac ${p}.java
	javac ${p2}.java

#################################
# End
#################################